name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]

permissions:
      id-token: write
      contents: read

jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: 'Azure OIDC login with federated principal'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

       
      - name: Unchecked Allow Azure services access to database to check authentication
        uses: azure/sql-action@v2
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './Database.sqlproj'
          action: 'publish'
  s3-cdk-stack-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dotnet AWS CDK GitHub Actions
        uses: P47Phoenix/dotnet-cdk-action@v1.0.12
      with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'

      - name: cdk deploy
        uses: P47Phoenix/dotnet-cdk-action@v1
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'CdkTipsTricksStack'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'

      - name: cdk synth
        uses: P47Phoenix/dotnet-cdk-action@v1
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.16.2'
          working_dir: 'src'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'