name: Deploy AWS CDK Stack
on:
  push:
    branches: [ develop ]

jobs: 
  s3_cdk_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another repository
        uses: actions/checkout@v2
        with:
          repository: ravichandranjv/cdk-stacks
          ref: develop
      - name: diff
        uses: P47Phoenix/dotnet-cdk-action@v1.0.12
        with:
          cdk_subcommand: 'diff'
          working_dir: 'src'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
      - name: Destroy after checking diff status
        uses: P47Phoenix/dotnet-cdk-action@v1.0.12
        with:
          cdk_subcommand: 'deploy'
          working_dir: 'src'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'

