name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]
permissions:
      id-token: write
      contents: read
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Log in with Azure credentials of service principal
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
       
      - name: Unchecked Allow Azure services access to database to check authentication
        uses: azure/sql-action@v2
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './Database.sqlproj'
          action: 'publish'