name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]
jobs:
  print-connstringS:
    name: Print connection
    runs-on: ubuntu-latest
    steps:
    - name: Print the connection string to STDOUT
      run:
        echo ${{ secrets.AZURE_SQL_CONNECTION_STRING }} | sed 's/./& /g' 
  Build:
    name: Build sql action
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Azure SQL Deploy
      uses: azure/sql-action@v2
      with:        
        path: './Database.sqlproj'
        action: 'publish'