name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]
jobs:
  print-connstringS:
    name: Print connection
    runs-on: ubuntu-latest
    steps:
      run:
        echo "Connection string is ${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
  Build:
    name: Build sql action
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      uses: azure/sql-action@v2
      with:        
        path: './Database.sqlproj'
        action: 'publish'