name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]
jobs: 
  build:
    name: Build sql action
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    -name: Azure login
      uses: azure/login@v1
    - name: Azure SQL Deploy
      uses: azure/sql-action@v2
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './Database.sqlproj'
        action: 'publish'