name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]
env:
  connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
jobs:
  print-connstringS:
    name: Print connection
    runs-on: ubuntu-latest
    steps:
    - name: Print the connection string to STDOUT
      run: echo The connection string is $connection-string
  Build:
    name: Build sql action
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Azure SQL Deploy
      uses: azure/sql-action@v2
      with:        
        path: './Database.sqlproj'
        action: 'publish'