name: Deploy EF Azure Database
on:
  push:
    branches: [ develop ]
jobs:
  print-username:
    name: Print username
    runs-on: ubuntu-latest
    steps:
    - name: Print the USER name to STDOUT
      run: echo The username is ${{ inputs.username }} and connection string is $secrets.AZURE_SQL_CONNECTION_STRING
  Build:
    name: Build sql action
    runs-on: ubuntu-latest
    env:
      connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Azure SQL Deploy
      uses: azure/sql-action@v2
      with:        
        path: './Database.sqlproj'
        action: 'publish'