name: Deploy EF Azure Database
on:
  workflow_call:
    inputs:
      username:
        description: 'Username passed from the caller workflow'
        default: 'jv ravichandran'
        required: false
        type: string
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - 'develop/**'
  push:
    branches: [ develop ]
jobs:
  print-username:
    name: Print username
    runs-on: ubuntu-latest
    steps:
    - name: Print the USER name to STDOUT
      run: echo The username is ${{ inputs.username }}
  Build:
    name: Build sql action
    runs-on: ubuntu-latest
    steps:
    - name: Azure SQL Deploy
      uses: actions/checkout@v3
      uses: azure/sql-action@v2
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './Database.sqlproj'
        action: 'publish'